# Generated by Django 2.0.13 on 2019-07-05 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20190705_1515'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_order', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 15, 52, 778230))),
                ('cost', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ordered_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0)),
                ('rating_prov', models.PositiveIntegerField(default=0)),
                ('rating_cust', models.PositiveIntegerField(default=0)),
                ('feedback_prov', models.CharField(max_length=100, null=True)),
                ('feedback_cust', models.CharField(max_length=100, null=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.order')),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ratecount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='custid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
