# Generated by Django 2.0.13 on 2019-07-06 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190706_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_service',
            name='expTime',
        ),
        migrations.AddField(
            model_name='ordered_service',
            name='expDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ordered_service',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
