# Generated by Django 2.0.13 on 2019-07-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190706_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_service',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordered_service',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
