# Generated by Django 2.0.13 on 2019-09-01 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_search_history_custid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='regdate',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
