# Generated by Django 2.0.13 on 2019-09-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customer_regdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='regdate',
        ),
    ]
