# Generated by Django 2.0.13 on 2019-09-12 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190908_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedcustomer',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(default=1000000000, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(1999999999)])),
            ],
        ),
    ]
