# Generated by Django 2.0.13 on 2019-06-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_provider_adminid'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowed_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
        migrations.RenameModel(
            old_name='admin',
            new_name='admin1',
        ),
    ]
