# Generated by Django 2.0.13 on 2019-06-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_provider_adminid'),
        ('admins', '0002_auto_20190629_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin1',
            new_name='admin_model',
        ),
    ]
