# Generated by Django 2.0.13 on 2019-06-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servname', models.CharField(max_length=100, unique=True)),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.category')),
            ],
        ),
    ]
