# Generated by Django 2.0.13 on 2019-06-27 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(default=1000000000, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(1999999999)])),
                ('password', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.category')),
            ],
        ),
        migrations.CreateModel(
            name='requested_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.requested_provider')),
            ],
        ),
    ]
