# Generated by Django 2.0.13 on 2019-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_requested_provider_requested_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_provider',
            name='idImage',
            field=models.ImageField(blank=True, upload_to='id_image/'),
        ),
    ]
