# Generated by Django 2.0.13 on 2019-06-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20190629_2049'),
        ('provider', '0006_remove_provider_adminid'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='adminid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.admin_model'),
        ),
    ]
