# Generated by Django 2.0.13 on 2019-07-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_provider_adminid'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('ratecount', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('looking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sp_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spImage', models.ImageField(null=True, upload_to='spImage/')),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='catImage',
            field=models.ImageField(null=True, upload_to='categoryImage/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='provImage',
            field=models.ImageField(null=True, upload_to='providerImage/'),
        ),
        migrations.AddField(
            model_name='service',
            name='servImage',
            field=models.ImageField(null=True, upload_to='serviceImage/'),
        ),
        migrations.AddField(
            model_name='service_provider',
            name='provid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
        migrations.AddField(
            model_name='service_provider',
            name='servid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service'),
        ),
    ]
