# Generated by Django 2.0.13 on 2019-07-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20190705_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provImage',
            field=models.ImageField(default='default-user.png', upload_to='providerImage/'),
        ),
    ]
