# Generated by Django 2.0.13 on 2019-07-20 05:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190713_2006'),
        ('provider', '0010_auto_20190711_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ordered_service')),
                ('provid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.PositiveIntegerField(default=1)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('msg', models.CharField(max_length=500)),
                ('inboxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.inbox')),
            ],
        ),
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=100)),
                ('discount', models.PositiveIntegerField(default=1000000000, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(1999999999)])),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service_provider')),
            ],
        ),
    ]
