# Generated by Django 2.0.13 on 2019-07-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_inbox_message_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='ordered_service',
            new_name='osid',
        ),
    ]
