# Generated by Django 2.0.13 on 2019-09-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190720_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(default='Dhaka', max_length=100),
            preserve_default=False,
        ),
    ]
