# Generated by Django 2.0.13 on 2019-09-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_provider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='joindate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
