# Generated by Django 2.0.13 on 2019-09-01 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_service_provider_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_provider',
            name='joindate',
        ),
        migrations.AddField(
            model_name='provider',
            name='joindate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
