# Generated by Django 2.0.13 on 2019-09-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20190901_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='joindate',
            new_name='time',
        ),
    ]
