# Generated by Django 2.0.13 on 2019-09-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_auto_20190901_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='time',
        ),
    ]
