# Generated by Django 2.0.13 on 2019-09-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0018_deletedprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='spid',
        ),
        migrations.DeleteModel(
            name='promo',
        ),
    ]
